sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t search-boot:latest .
      - docker run -d -p 127.0.0.1:8080:8080 search-boot:latest /bin/sh -c "curl localhost:8080/app/health"
      - docker ps -a
      - docker images
    - stage: Push to Docker Hub
      if: branch = master
        - docker tag search-boot:latest $DOCKER_USERNAME/search-boot:latest
        - docker push $DOCKER_USERNAME/search-boot:latest
